name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup stack
      uses: mstksg/setup-stack@v1
   
    - name: Build
      run: stack build
    
    - name: Run tests
      run: stack test
